#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_BUILD_LIB = $(INC)
CFLAGS_BUILD_LIB = $(CFLAGS) -std=c++11 -g
RESINC_BUILD_LIB = $(RESINC)
RCFLAGS_BUILD_LIB = $(RCFLAGS)
LIBDIR_BUILD_LIB = $(LIBDIR)
LIB_BUILD_LIB = $(LIB)
LDFLAGS_BUILD_LIB = $(LDFLAGS)
OBJDIR_BUILD_LIB = obj/Debug
DEP_BUILD_LIB = 
OUT_BUILD_LIB = bin/Debug/libCppLambdaTest.a

OBJ_BUILD_LIB = $(OBJDIR_BUILD_LIB)/LTest.o

all: build_lib

clean: clean_build_lib

before_build_lib: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_BUILD_LIB) || mkdir -p $(OBJDIR_BUILD_LIB)

after_build_lib: 

build_lib: before_build_lib out_build_lib after_build_lib

out_build_lib: before_build_lib $(OBJ_BUILD_LIB) $(DEP_BUILD_LIB)
	$(AR) rcs $(OUT_BUILD_LIB) $(OBJ_BUILD_LIB)

$(OBJDIR_BUILD_LIB)/LTest.o: LTest.cpp
	$(CXX) $(CFLAGS_BUILD_LIB) $(INC_BUILD_LIB) -c LTest.cpp -o $(OBJDIR_BUILD_LIB)/LTest.o

clean_build_lib: 
	rm -f $(OBJ_BUILD_LIB) $(OUT_BUILD_LIB)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_BUILD_LIB)

.PHONY: before_build_lib after_build_lib clean_build_lib

